### ISSUE TITLE
No support of bulkcopy an IMAGE column

### ISSUE THREAD

**Issue by michaelcplusplus** [microsoft/go-mssqldb#187]
**Describe the bug**

I get this error message when I try to copy a table with an IMAGE column

```
Exception message:
not implemented makeDecl for type 0x22
Stack trace:
github.com/microsoft/go-mssqldb.makeDecl({0x22, 0x0, 0x9, 0x7fffffff, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
	C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.6.0/types.go:1263 +0x8f9
github.com/microsoft/go-mssqldb.(*Bulk).sendBulkCommand(0xc000000000, {0x4c4ff0, 0x7b7c20})
	C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.6.0/bulkcopy.go:104 +0x398
github.com/microsoft/go-mssqldb.(*Bulk).AddRow(0xc000000000, {0xc000002588, 0x2b, 0x2b})
	C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.6.0/bulkcopy.go:165 +0x3d
github.com/microsoft/go-mssqldb.(*copyin).Exec(0xc000008258, {0xc0000022c8, 0x2b, 0xc00040e030?})
	C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.6.0/bulkcopy_sql.go:83 +0x11a
database/sql.ctxDriverStmtExec({0x4c4ff0, 0x7b7c20}, {0x4c5108, 0xc000008258}, {0xc0002c0708, 0x2b, 0x2b?})
	C:/Program Files/Go/src/database/sql/ctxutil.go:77 +0x1ca
database/sql.resultFromStatement({0x4c4ff0, 0x7b7c20}, {0x4c4a40, 0xc00002e4c0}, 0xc00002e080, {0xc000353348, 0x2b, 0x2b})
	C:/Program Files/Go/src/database/sql/sql.go:2670 +0x13a
database/sql.(*Stmt).ExecContext.func1(0x0?)
	C:/Program Files/Go/src/database/sql/sql.go:2644 +0x9f
database/sql.(*DB).retry(0xc0003bda10?, 0xc0003bda10)
	C:/Program Files/Go/src/database/sql/sql.go:1566 +0x42
database/sql.(*Stmt).ExecContext(0xc00033c090?, {0x4c4ff0?, 0x7b7c20?}, {0xc000353348?, 0x4c3e88?, 0xc00033c0c8?})
	C:/Program Files/Go/src/database/sql/sql.go:2638 +0x16b
database/sql.(*Stmt).Exec(...)
	C:/Program Files/Go/src/database/sql/sql.go:2658
github.com/mpdv/bulk.(*CopyIn).Append(0xc00033c120, 0x2b?)
```

**Expected behavior**
Support of the IMAGE column type(typeImage) in the functions 
**types.go** 
func makeDecl(ti typeInfo) string
 and 
**bulkcopy.go** 
func (b *Bulk) makeParam(val DataValue, col columnStruct) (res param, err error) 

### Further technical details
SQL Server version: SQL Server 2019
Operating system: Windows 2019

**Comment by dlevy-msft-sql** [comment]
Thank you for reporting this. IMAGE column bulk copy is supported in the current version of the driver. The bulk copy implementation handles IMAGE columns (as well as varbinary(max) and other large binary types) correctly. If you're still experiencing issues with a recent version, please don't hesitate to open a new issue with your reproduction details and we'll take a look. Closing as resolved. We appreciate your report!

**Comment by michaelcplusplus** [comment]
I got still this error message with github.com/microsoft/go-mssqldb v1.9.8

```
panic: not implemented makeDecl for type 0x22

goroutine 1 [running]:
github.com/microsoft/go-mssqldb.makeDecl({0x22, 0x0, 0x9, 0x7fffffff, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
        C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/types.go:1312 +0x8f9
github.com/microsoft/go-mssqldb.(*Bulk).sendBulkCommand(0xc000000180, {0x7ff723a2d0e0, 0x7ff7249e9f60})
        C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy.go:107 +0x439
github.com/microsoft/go-mssqldb.(*Bulk).AddRow(0xc000000180, {0xc0002bb608, 0x2b, 0x2b})
        C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy.go:168 +0x3d
github.com/microsoft/go-mssqldb.(*copyin).Exec(0xc000288798, {0xc0002bb348?, 0x2b?, 0x7ff723558277?})
        C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy_sql.go:83 +0x13d
database/sql.ctxDriverStmtExec({0x7ff723a2d0e0, 0x7ff7249e9f60}, {0x7ff723a2d380, 0xc000288798}, {0xc000098e08, 0x2b, 0x2b?})
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/ctxutil.go:77 +0x1bf
database/sql.resultFromStatement({0x7ff723a2d0e0, 0x7ff7249e9f60}, {0x7ff723a2c570, 0xc0000a4700}, 0xc000044880, {0xc000342588, 0x2b, 0x2b})
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2680 +0x125
database/sql.(*Stmt).ExecContext.func1(0x8?)
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2654 +0x9f
database/sql.(*DB).retry(0x0?, 0xc0001839e0)
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:1576 +0x42
database/sql.(*Stmt).ExecContext(0xc00016e3c0?, {0x7ff723a2d0e0?, 0x7ff7249e9f60?}, {0xc000342588?, 0x7ff7235e8988?, 0x7ff7235e9800?})
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2648 +0x165
database/sql.(*Stmt).Exec(...)
        C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2668
```

**Comment by dlevy-msft-sql** [comment]
> I got still this error message with github.com/microsoft/go-mssqldb v1.9.8
> 
> ```
> panic: not implemented makeDecl for type 0x22
> 
> goroutine 1 [running]:
> github.com/microsoft/go-mssqldb.makeDecl({0x22, 0x0, 0x9, 0x7fffffff, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
>         C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/types.go:1312 +0x8f9
> github.com/microsoft/go-mssqldb.(*Bulk).sendBulkCommand(0xc000000180, {0x7ff723a2d0e0, 0x7ff7249e9f60})
>         C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy.go:107 +0x439
> github.com/microsoft/go-mssqldb.(*Bulk).AddRow(0xc000000180, {0xc0002bb608, 0x2b, 0x2b})
>         C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy.go:168 +0x3d
> github.com/microsoft/go-mssqldb.(*copyin).Exec(0xc000288798, {0xc0002bb348?, 0x2b?, 0x7ff723558277?})
>         C:/Users/ml/go/pkg/mod/github.com/microsoft/go-mssqldb@v1.9.8/bulkcopy_sql.go:83 +0x13d
> database/sql.ctxDriverStmtExec({0x7ff723a2d0e0, 0x7ff7249e9f60}, {0x7ff723a2d380, 0xc000288798}, {0xc000098e08, 0x2b, 0x2b?})
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/ctxutil.go:77 +0x1bf
> database/sql.resultFromStatement({0x7ff723a2d0e0, 0x7ff7249e9f60}, {0x7ff723a2c570, 0xc0000a4700}, 0xc000044880, {0xc000342588, 0x2b, 0x2b})
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2680 +0x125
> database/sql.(*Stmt).ExecContext.func1(0x8?)
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2654 +0x9f
> database/sql.(*DB).retry(0x0?, 0xc0001839e0)
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:1576 +0x42
> database/sql.(*Stmt).ExecContext(0xc00016e3c0?, {0x7ff723a2d0e0?, 0x7ff7249e9f60?}, {0xc000342588?, 0x7ff7235e8988?, 0x7ff7235e9800?})
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2648 +0x165
> database/sql.(*Stmt).Exec(...)
>         C:/Users/ml/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.7.windows-amd64/src/database/sql/sql.go:2668
> ```

Apologies for the premature close. You're right, the fix was not included in v1.9.8.

The fix landed on `main` via PR #239 (commit `17636aa`), which adds IMAGE (and XML) type support to `makeDecl` and bulk copy. It has not been included in a release yet.

In the meantime, you can use the `main` branch directly:

``````
go get github.com/microsoft/go-mssqldb@main
``````

This will be included in the next tagged release. Reopening until then.

**Comment by saurabh500** [comment]
@dlevy-msft-sql is this a matter of a new release at this point?

**Comment by dlevy-msft-sql** [comment]
> [David Levy (@dlevy-msft-sql)](https://github.com/dlevy-msft-sql) is this a matter of a new release at this point?

Yes. We just need to merge PR #380 to complete the release.

**Comment by dlevy-msft-sql** [comment]
> [David Levy (@dlevy-msft-sql)](https://github.com/dlevy-msft-sql) is this a matter of a new release at this point?

Correction, PR #239 landed in v1.10 on April 10th. The PR name did not follow the release please convention, so it was not included in the release notes.

**Comment by michaelcplusplus** [comment]
Thanks. With v1.10.0 it works now 👍
